#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Defines environment variables.
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

# Dont read global configs
unsetopt GLOBAL_RCS

# Set the path to dotzsh.
export DOTZSH="$HOME/.zsh"

# Source environment settings
source "$DOTZSH/env.zsh"

export GOPATH=$HOME/go

# Customize to your needs...
# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.rvm/bin # Add RVM to PATH for scripting
  /opt/sublime_text_3
  $HOME/.git-aliae/bin
  $HOME/android/sdk/{tools,platform-tools}
  $HOME/android/android-studio/bin
  /usr/local/{bin,sbin}
  $HOME/.local/bin
  $GOPATH/bin
  $path
)

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/workspace
export VIRTUAL_ENV_DISABLE_PROMPT=1
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
export VIRTUALENVWRAPPER_PYTHON='/usr/bin/python3.6'
export VAGRANT_DEFAULT_PROVIDER=libvirt

